<?php
declare(strict_types=1);

return function (PDO $pdo): void {
    $questions = [
        [
            'subject' => 'biology', 'topic' => 'cell-biology', 'difficulty' => 'easy',
            'question' => 'Which organelle is known as the powerhouse of the cell?',
            'explanation' => 'Mitochondria generate ATP through cellular respiration, earning them the nickname "powerhouse of the cell."',
            'options' => [['A', 'Nucleus', false], ['B', 'Mitochondria', true], ['C', 'Ribosome', false], ['D', 'Golgi apparatus', false]],
        ],
        [
            'subject' => 'chemistry', 'topic' => 'atmospheric-chemistry', 'difficulty' => 'medium',
            'question' => "What is the most abundant gas in Earth's atmosphere?",
            'explanation' => 'Nitrogen makes up about 78% of the atmosphere by volume.',
            'options' => [['A', 'Nitrogen', true], ['B', 'Oxygen', false], ['C', 'Carbon Dioxide', false], ['D', 'Argon', false]],
        ],
        [
            'subject' => 'biology', 'topic' => 'digestive-system', 'difficulty' => 'hard',
            'question' => 'Which enzyme breaks down starch into maltose in the digestive system?',
            'explanation' => 'Amylase, found in saliva and pancreatic secretions, hydrolyzes starch into maltose.',
            'options' => [['A', 'Amylase', true], ['B', 'Lipase', false], ['C', 'Pepsin', false], ['D', 'Trypsin', false]],
        ],
        [
            'subject' => 'mathematics', 'topic' => 'calculus', 'difficulty' => 'medium',
            'question' => 'What is the derivative of x² with respect to x?',
            'explanation' => 'Using the power rule, d/dx(x^n) = n·x^(n-1), so the derivative of x² is 2x.',
            'options' => [['A', 'x', false], ['B', '2x', true], ['C', 'x²', false], ['D', '2', false]],
        ],
        [
            'subject' => 'physics', 'topic' => 'electricity', 'difficulty' => 'medium',
            'question' => 'What is the SI unit of electric current?',
            'explanation' => 'The ampere (A) is the SI base unit of electric current.',
            'options' => [['A', 'Volt', false], ['B', 'Ampere', true], ['C', 'Ohm', false], ['D', 'Watt', false]],
        ],
        [
            'subject' => 'general-knowledge', 'topic' => 'geography', 'difficulty' => 'easy',
            'question' => 'Which planet is known as the Red Planet?',
            'explanation' => 'Mars appears red due to iron oxide (rust) on its surface.',
            'options' => [['A', 'Venus', false], ['B', 'Mars', true], ['C', 'Jupiter', false], ['D', 'Saturn', false]],
        ],

        // ===================== BIOLOGY =====================
        ['subject' => 'biology', 'topic' => 'cell-biology', 'difficulty' => 'easy', 'question' => 'What is the basic structural and functional unit of life?', 'explanation' => 'The cell is the smallest unit capable of independent life functions.', 'options' => [['A', 'Cell', true], ['B', 'Tissue', false], ['C', 'Organ', false], ['D', 'Organelle', false]]],
        ['subject' => 'biology', 'topic' => 'cell-biology', 'difficulty' => 'easy', 'question' => 'Which part of the cell contains genetic material (DNA)?', 'explanation' => 'The nucleus houses the cell\'s chromosomal DNA.', 'options' => [['A', 'Cytoplasm', false], ['B', 'Nucleus', true], ['C', 'Ribosome', false], ['D', 'Lysosome', false]]],
        ['subject' => 'biology', 'topic' => 'cell-biology', 'difficulty' => 'medium', 'question' => 'Which organelle is responsible for protein synthesis?', 'explanation' => 'Ribosomes translate mRNA into proteins.', 'options' => [['A', 'Ribosome', true], ['B', 'Golgi apparatus', false], ['C', 'Lysosome', false], ['D', 'Vacuole', false]]],
        ['subject' => 'biology', 'topic' => 'cell-biology', 'difficulty' => 'hard', 'question' => 'What is the term for programmed cell death?', 'explanation' => 'Apoptosis is a regulated process of cell self-destruction.', 'options' => [['A', 'Mitosis', false], ['B', 'Apoptosis', true], ['C', 'Meiosis', false], ['D', 'Necrosis', false]]],
        ['subject' => 'biology', 'topic' => 'cell-biology', 'difficulty' => 'easy', 'question' => 'Which structure controls what enters and leaves the cell?', 'explanation' => 'The cell membrane is selectively permeable, regulating the movement of substances.', 'options' => [['A', 'Cell wall', false], ['B', 'Cell membrane', true], ['C', 'Nucleolus', false], ['D', 'Cytoskeleton', false]]],
        ['subject' => 'biology', 'topic' => 'cell-biology', 'difficulty' => 'medium', 'question' => 'Plant cells differ from animal cells mainly because plant cells have:', 'explanation' => 'Plant cells have a rigid cell wall and chloroplasts, which animal cells lack.', 'options' => [['A', 'Cell wall and chloroplasts', true], ['B', 'Mitochondria only', false], ['C', 'Ribosomes only', false], ['D', 'Nucleus only', false]]],
        ['subject' => 'biology', 'topic' => 'cell-biology', 'difficulty' => 'medium', 'question' => 'Which cell organelle is involved in packaging and modifying proteins for secretion?', 'explanation' => 'The Golgi apparatus modifies, sorts, and packages proteins for secretion or use within the cell.', 'options' => [['A', 'Golgi apparatus', true], ['B', 'Nucleus', false], ['C', 'Mitochondria', false], ['D', 'Peroxisome', false]]],
        ['subject' => 'biology', 'topic' => 'cell-biology', 'difficulty' => 'medium', 'question' => 'What type of cell lacks a true nucleus?', 'explanation' => 'Prokaryotic cells, such as bacteria, lack a membrane-bound nucleus.', 'options' => [['A', 'Eukaryotic cell', false], ['B', 'Prokaryotic cell', true], ['C', 'Plant cell', false], ['D', 'Animal cell', false]]],
        ['subject' => 'biology', 'topic' => 'cell-biology', 'difficulty' => 'easy', 'question' => 'Which scientist first used the term "cell" after observing thin slices of cork under a microscope?', 'explanation' => 'Robert Hooke coined the word "cell" in 1665 when the boxy compartments of cork reminded him of monastery cells.', 'options' => [['A', 'Anton van Leeuwenhoek', false], ['B', 'Robert Hooke', true], ['C', 'Rudolf Virchow', false], ['D', 'Theodor Schwann', false]]],
        ['subject' => 'biology', 'topic' => 'cell-biology', 'difficulty' => 'easy', 'question' => 'In which organelle does photosynthesis take place in plant cells?', 'explanation' => 'Chloroplasts contain chlorophyll on their thylakoid membranes and trap light energy to synthesise glucose.', 'options' => [['A', 'Chloroplast', true], ['B', 'Mitochondrion', false], ['C', 'Vacuole', false], ['D', 'Nucleus', false]]],
        ['subject' => 'biology', 'topic' => 'cell-biology', 'difficulty' => 'easy', 'question' => 'Which cell organelle is often called the "suicidal bag" of the cell?', 'explanation' => 'Lysosomes contain hydrolytic enzymes that can digest the whole cell if their membrane ruptures, hence the name suicidal bags.', 'options' => [['A', 'Peroxisome', false], ['B', 'Lysosome', true], ['C', 'Ribosome', false], ['D', 'Vacuole', false]]],
        ['subject' => 'biology', 'topic' => 'cell-biology', 'difficulty' => 'easy', 'question' => 'Which type of ribosome is characteristically found in prokaryotic cells?', 'explanation' => 'Prokaryotes possess smaller 70S ribosomes, whereas the cytoplasm of eukaryotes contains 80S ribosomes.', 'options' => [['A', '80S', false], ['B', '70S', true], ['C', '60S', false], ['D', '55S', false]]],
        ['subject' => 'biology', 'topic' => 'cell-biology', 'difficulty' => 'easy', 'question' => 'Which rigid outer layer is present in plant cells but absent in animal cells?', 'explanation' => 'Plant cells are enclosed by a cellulose cell wall that provides shape and mechanical support, a feature lacking in animal cells.', 'options' => [['A', 'Plasma membrane', false], ['B', 'Cell wall', true], ['C', 'Glycocalyx', false], ['D', 'Tonoplast', false]]],
        ['subject' => 'biology', 'topic' => 'cell-biology', 'difficulty' => 'easy', 'question' => 'Which two scientists are jointly credited with first formulating the cell theory?', 'explanation' => 'Matthias Schleiden (for plants) and Theodor Schwann (for animals) proposed the cell theory around 1838 to 1839.', 'options' => [['A', 'Watson and Crick', false], ['B', 'Schleiden and Schwann', true], ['C', 'Darwin and Wallace', false], ['D', 'Mendel and Morgan', false]]],
        ['subject' => 'biology', 'topic' => 'cell-biology', 'difficulty' => 'medium', 'question' => 'The statement "Omnis cellula e cellula", meaning every cell arises from a pre-existing cell, is credited to which scientist?', 'explanation' => 'Rudolf Virchow extended the cell theory in the 1850s by establishing that new cells come only from division of existing cells.', 'options' => [['A', 'Robert Brown', false], ['B', 'Theodor Schwann', false], ['C', 'Rudolf Virchow', true], ['D', 'Louis Pasteur', false]]],
        ['subject' => 'biology', 'topic' => 'cell-biology', 'difficulty' => 'medium', 'question' => 'The widely accepted fluid mosaic model of the plasma membrane was proposed in 1972 by which pair of scientists?', 'explanation' => 'Singer and Nicolson described the membrane as a fluid lipid bilayer with proteins embedded in a mosaic pattern.', 'options' => [['A', 'Singer and Nicolson', true], ['B', 'Gorter and Grendel', false], ['C', 'Danielli and Davson', false], ['D', 'Robertson and Palade', false]]],
        ['subject' => 'biology', 'topic' => 'cell-biology', 'difficulty' => 'medium', 'question' => 'Which pair of organelles are both double membrane bound and semiautonomous, containing their own DNA?', 'explanation' => 'Mitochondria and chloroplasts each have two membranes and their own DNA and ribosomes, allowing partial self-replication.', 'options' => [['A', 'Golgi apparatus and lysosome', false], ['B', 'Nucleus and vacuole', false], ['C', 'Mitochondrion and chloroplast', true], ['D', 'Ribosome and peroxisome', false]]],
        ['subject' => 'biology', 'topic' => 'cell-biology', 'difficulty' => 'medium', 'question' => 'Why is the rough endoplasmic reticulum described as "rough"?', 'explanation' => 'Ribosomes attached to its outer surface give the rough ER a granular look and enable it to synthesise proteins.', 'options' => [['A', 'It has ribosomes on its surface', true], ['B', 'It stores calcium ions', false], ['C', 'It synthesises only lipids', false], ['D', 'It lacks a membrane', false]]],
        ['subject' => 'biology', 'topic' => 'cell-biology', 'difficulty' => 'medium', 'question' => 'What is the main role of nuclear pores in the nuclear envelope?', 'explanation' => 'Nuclear pores allow controlled two-way movement of RNA and proteins between the nucleus and the cytoplasm.', 'options' => [['A', 'Producing ribosomal subunits', false], ['B', 'Exchange of RNA and proteins with cytoplasm', true], ['C', 'Synthesising ATP', false], ['D', 'Anchoring chromosomes', false]]],
        ['subject' => 'biology', 'topic' => 'cell-biology', 'difficulty' => 'medium', 'question' => 'Which Belgian scientist discovered lysosomes and later received a Nobel Prize for the work?', 'explanation' => 'Christian de Duve discovered lysosomes in 1955 and shared the 1974 Nobel Prize in Physiology or Medicine.', 'options' => [['A', 'Camillo Golgi', false], ['B', 'George Palade', false], ['C', 'Christian de Duve', true], ['D', 'Albert Claude', false]]],
        ['subject' => 'biology', 'topic' => 'cell-biology', 'difficulty' => 'hard', 'question' => 'The 80S ribosome of eukaryotes is composed of which two subunits?', 'explanation' => 'The eukaryotic 80S ribosome consists of a large 60S subunit and a small 40S subunit.', 'options' => [['A', '50S and 30S', false], ['B', '60S and 40S', true], ['C', '70S and 30S', false], ['D', '40S and 20S', false]]],
        ['subject' => 'biology', 'topic' => 'cell-biology', 'difficulty' => 'hard', 'question' => 'Enzymes destined for lysosomes are specifically tagged with which molecular marker in the Golgi apparatus?', 'explanation' => 'Lysosomal hydrolases are marked with mannose-6-phosphate, which directs them into acidified vesicles that become lysosomes.', 'options' => [['A', 'Mannose-6-phosphate', true], ['B', 'Glucose-1-phosphate', false], ['C', 'Ubiquitin', false], ['D', 'Sialic acid', false]]],
        ['subject' => 'biology', 'topic' => 'cell-biology', 'difficulty' => 'hard', 'question' => 'Which scientist is credited with discovering the cell nucleus in 1831?', 'explanation' => 'Robert Brown first described the nucleus as a constant feature of plant cells in 1831.', 'options' => [['A', 'Robert Hooke', false], ['B', 'Rudolf Virchow', false], ['C', 'Robert Brown', true], ['D', 'Matthias Schleiden', false]]],
        ['subject' => 'biology', 'topic' => 'cell-biology', 'difficulty' => 'hard', 'question' => 'The infoldings of the inner mitochondrial membrane that increase surface area for ATP synthesis are called what?', 'explanation' => 'Cristae are folds of the inner mitochondrial membrane that house the electron transport chain and ATP synthase.', 'options' => [['A', 'Grana', false], ['B', 'Thylakoids', false], ['C', 'Cristae', true], ['D', 'Lamellae', false]]],

        ['subject' => 'biology', 'topic' => 'genetics', 'difficulty' => 'easy', 'question' => 'Who is known as the father of genetics?', 'explanation' => 'Gregor Mendel\'s pea plant experiments laid the foundation for modern genetics.', 'options' => [['A', 'Charles Darwin', false], ['B', 'Gregor Mendel', true], ['C', 'James Watson', false], ['D', 'Francis Crick', false]]],
        ['subject' => 'biology', 'topic' => 'genetics', 'difficulty' => 'easy', 'question' => 'DNA stands for:', 'explanation' => 'DNA is short for deoxyribonucleic acid, the molecule that carries genetic information.', 'options' => [['A', 'Deoxyribonucleic acid', true], ['B', 'Denatured nucleic acid', false], ['C', 'Dual nucleic acid', false], ['D', 'Deoxyribose nuclear acid', false]]],
        ['subject' => 'biology', 'topic' => 'genetics', 'difficulty' => 'medium', 'question' => 'A person with genotype Aa is called:', 'explanation' => 'Heterozygous describes an organism with two different alleles for a gene.', 'options' => [['A', 'Homozygous', false], ['B', 'Heterozygous', true], ['C', 'Hemizygous', false], ['D', 'Homogenous', false]]],
        ['subject' => 'biology', 'topic' => 'genetics', 'difficulty' => 'medium', 'question' => 'How many chromosomes are present in a normal human somatic cell?', 'explanation' => 'Human somatic cells are diploid, containing 46 chromosomes (23 pairs).', 'options' => [['A', '23', false], ['B', '46', true], ['C', '44', false], ['D', '48', false]]],
        ['subject' => 'biology', 'topic' => 'genetics', 'difficulty' => 'medium', 'question' => 'The physical expression of a genetic trait is called the:', 'explanation' => 'Phenotype refers to the observable characteristics resulting from genotype and environment.', 'options' => [['A', 'Genotype', false], ['B', 'Phenotype', true], ['C', 'Allele', false], ['D', 'Locus', false]]],
        ['subject' => 'biology', 'topic' => 'genetics', 'difficulty' => 'medium', 'question' => 'Which scientists discovered the double helix structure of DNA?', 'explanation' => 'James Watson and Francis Crick proposed the double helix model of DNA in 1953.', 'options' => [['A', 'Watson and Crick', true], ['B', 'Mendel and Darwin', false], ['C', 'Pasteur and Koch', false], ['D', 'Fleming and Florey', false]]],
        ['subject' => 'biology', 'topic' => 'genetics', 'difficulty' => 'easy', 'question' => 'A change in the DNA sequence is called a:', 'explanation' => 'Mutations are alterations in the nucleotide sequence of DNA.', 'options' => [['A', 'Mutation', true], ['B', 'Translation', false], ['C', 'Transcription', false], ['D', 'Replication', false]]],
        ['subject' => 'biology', 'topic' => 'genetics', 'difficulty' => 'easy', 'question' => 'Sex chromosomes in human males are:', 'explanation' => 'Human males typically have one X and one Y chromosome (XY).', 'options' => [['A', 'XX', false], ['B', 'XY', true], ['C', 'YY', false], ['D', 'XO', false]]],
        ['subject' => 'biology', 'topic' => 'genetics', 'difficulty' => 'easy', 'question' => 'Mendel carried out his classic inheritance experiments on which plant?', 'explanation' => 'Mendel used the garden pea, Pisum sativum, because of its clear contrasting traits and easy controlled pollination.', 'options' => [['A', 'Maize', false], ['B', 'Snapdragon', false], ['C', 'Garden pea', true], ['D', 'Sweet pea', false]]],
        ['subject' => 'biology', 'topic' => 'genetics', 'difficulty' => 'easy', 'question' => 'In DNA, adenine always pairs with which nitrogenous base?', 'explanation' => 'Following Chargaff\'s base pairing rules, adenine pairs with thymine through two hydrogen bonds.', 'options' => [['A', 'Guanine', false], ['B', 'Cytosine', false], ['C', 'Uracil', false], ['D', 'Thymine', true]]],
        ['subject' => 'biology', 'topic' => 'genetics', 'difficulty' => 'easy', 'question' => 'Down syndrome in humans is caused by an extra copy of which chromosome?', 'explanation' => 'Down syndrome results from trisomy of chromosome 21, giving a total of 47 chromosomes.', 'options' => [['A', 'Chromosome 18', false], ['B', 'Chromosome 13', false], ['C', 'Chromosome 21', true], ['D', 'The X chromosome', false]]],
        ['subject' => 'biology', 'topic' => 'genetics', 'difficulty' => 'easy', 'question' => 'Which codon acts as the start signal for translation and also codes for methionine?', 'explanation' => 'AUG is the universal start codon that initiates translation and specifies the amino acid methionine.', 'options' => [['A', 'UAA', false], ['B', 'AUG', true], ['C', 'UGA', false], ['D', 'GUA', false]]],
        ['subject' => 'biology', 'topic' => 'genetics', 'difficulty' => 'medium', 'question' => 'Mendel\'s law stating that the two alleles of a gene separate during gamete formation is known as the law of what?', 'explanation' => 'The law of segregation states that paired alleles separate so each gamete receives only one allele of each gene.', 'options' => [['A', 'Dominance', false], ['B', 'Independent assortment', false], ['C', 'Segregation', true], ['D', 'Linkage', false]]],
        ['subject' => 'biology', 'topic' => 'genetics', 'difficulty' => 'medium', 'question' => 'What is the phenotypic ratio in the F2 generation of a typical dihybrid cross?', 'explanation' => 'A dihybrid cross between double heterozygotes yields a 9:3:3:1 phenotypic ratio in the F2 generation.', 'options' => [['A', '3:1', false], ['B', '1:2:1', false], ['C', '9:3:3:1', true], ['D', '1:1:1:1', false]]],
        ['subject' => 'biology', 'topic' => 'genetics', 'difficulty' => 'medium', 'question' => 'How many hydrogen bonds form between guanine and cytosine in a DNA molecule?', 'explanation' => 'Guanine pairs with cytosine through three hydrogen bonds, making G-C pairs more stable than A-T pairs.', 'options' => [['A', 'One', false], ['B', 'Two', false], ['C', 'Three', true], ['D', 'Four', false]]],
        ['subject' => 'biology', 'topic' => 'genetics', 'difficulty' => 'medium', 'question' => 'Colour blindness and haemophilia in humans are examples of which pattern of inheritance?', 'explanation' => 'Both conditions are X-linked recessive traits, so they appear far more often in males, who have a single X chromosome.', 'options' => [['A', 'Autosomal dominant', false], ['B', 'X-linked recessive', true], ['C', 'Y-linked', false], ['D', 'Mitochondrial', false]]],
        ['subject' => 'biology', 'topic' => 'genetics', 'difficulty' => 'medium', 'question' => 'In the ABO blood group system, the alleles IA and IB show which relationship to each other?', 'explanation' => 'IA and IB are codominant, so a person carrying both alleles expresses both A and B antigens and has blood group AB.', 'options' => [['A', 'Complete dominance', false], ['B', 'Codominance', true], ['C', 'Incomplete dominance', false], ['D', 'Epistasis', false]]],
        ['subject' => 'biology', 'topic' => 'genetics', 'difficulty' => 'medium', 'question' => 'Which of the following is a stop codon that terminates translation?', 'explanation' => 'UAA, UAG and UGA are stop codons that signal the end of translation; UAA is one of them.', 'options' => [['A', 'AUG', false], ['B', 'GUG', false], ['C', 'UAA', true], ['D', 'CCA', false]]],
        ['subject' => 'biology', 'topic' => 'genetics', 'difficulty' => 'medium', 'question' => 'A person with the sex chromosome constitution XXY is affected by which condition?', 'explanation' => 'The XXY constitution causes Klinefelter syndrome, in which an affected male has one extra X chromosome.', 'options' => [['A', 'Turner syndrome', false], ['B', 'Down syndrome', false], ['C', 'Klinefelter syndrome', true], ['D', 'Patau syndrome', false]]],
        ['subject' => 'biology', 'topic' => 'genetics', 'difficulty' => 'hard', 'question' => 'How many different alleles determine the ABO blood group in the human population?', 'explanation' => 'The ABO gene has three alleles, IA, IB and i, making it a classic example of multiple allelism.', 'options' => [['A', 'Two', false], ['B', 'Three', true], ['C', 'Four', false], ['D', 'Six', false]]],
        ['subject' => 'biology', 'topic' => 'genetics', 'difficulty' => 'hard', 'question' => 'Chargaff\'s rules state that in a DNA molecule the amount of adenine equals thymine and the amount of guanine equals which base?', 'explanation' => 'Chargaff observed that A equals T and G equals C, reflecting the complementary base pairing of the two strands.', 'options' => [['A', 'Cytosine', true], ['B', 'Adenine', false], ['C', 'Uracil', false], ['D', 'Thymine', false]]],
        ['subject' => 'biology', 'topic' => 'genetics', 'difficulty' => 'hard', 'question' => 'The concept of gene linkage was first demonstrated by Thomas Hunt Morgan using which experimental organism?', 'explanation' => 'Morgan established linkage and sex-linked inheritance using the fruit fly Drosophila melanogaster around 1910.', 'options' => [['A', 'Garden pea', false], ['B', 'Fruit fly (Drosophila)', true], ['C', 'Bread mould', false], ['D', 'Escherichia coli', false]]],
        ['subject' => 'biology', 'topic' => 'genetics', 'difficulty' => 'hard', 'question' => 'Which blood group is considered the universal recipient in ABO transfusion?', 'explanation' => 'Blood group AB has no anti-A or anti-B antibodies in its plasma, so it can receive all ABO blood types.', 'options' => [['A', 'Group O', false], ['B', 'Group A', false], ['C', 'Group B', false], ['D', 'Group AB', true]]],

        ['subject' => 'biology', 'topic' => 'human-physiology', 'difficulty' => 'easy', 'question' => 'Which organ pumps blood throughout the human body?', 'explanation' => 'The heart is a muscular pump that circulates blood through the body.', 'options' => [['A', 'Liver', false], ['B', 'Heart', true], ['C', 'Kidney', false], ['D', 'Lungs', false]]],
        ['subject' => 'biology', 'topic' => 'human-physiology', 'difficulty' => 'easy', 'question' => 'The normal human body temperature is approximately:', 'explanation' => 'Normal human body temperature averages around 37°C (98.6°F).', 'options' => [['A', '37°C', true], ['B', '40°C', false], ['C', '35°C', false], ['D', '39°C', false]]],
        ['subject' => 'biology', 'topic' => 'human-physiology', 'difficulty' => 'medium', 'question' => 'Which organ is primarily responsible for filtering blood and producing urine?', 'explanation' => 'The kidneys filter waste products from blood to form urine.', 'options' => [['A', 'Liver', false], ['B', 'Kidney', true], ['C', 'Spleen', false], ['D', 'Pancreas', false]]],
        ['subject' => 'biology', 'topic' => 'human-physiology', 'difficulty' => 'easy', 'question' => 'The largest organ of the human body is the:', 'explanation' => 'The skin is the largest organ, covering the entire body surface.', 'options' => [['A', 'Liver', false], ['B', 'Skin', true], ['C', 'Heart', false], ['D', 'Brain', false]]],
        ['subject' => 'biology', 'topic' => 'human-physiology', 'difficulty' => 'medium', 'question' => 'Which gland is known as the "master gland" of the endocrine system?', 'explanation' => 'The pituitary gland regulates many other endocrine glands in the body.', 'options' => [['A', 'Thyroid', false], ['B', 'Pituitary gland', true], ['C', 'Adrenal gland', false], ['D', 'Pancreas', false]]],
        ['subject' => 'biology', 'topic' => 'human-physiology', 'difficulty' => 'medium', 'question' => 'Insulin, which regulates blood sugar, is produced by the:', 'explanation' => 'The pancreas secretes insulin from its beta cells to regulate blood glucose.', 'options' => [['A', 'Liver', false], ['B', 'Pancreas', true], ['C', 'Kidney', false], ['D', 'Spleen', false]]],
        ['subject' => 'biology', 'topic' => 'human-physiology', 'difficulty' => 'medium', 'question' => 'The human skeletal system consists of how many bones in adults?', 'explanation' => 'The adult human skeleton typically has 206 bones.', 'options' => [['A', '206', true], ['B', '300', false], ['C', '186', false], ['D', '250', false]]],
        ['subject' => 'biology', 'topic' => 'human-physiology', 'difficulty' => 'medium', 'question' => 'Which part of the brain controls balance and coordination?', 'explanation' => 'The cerebellum is responsible for coordinating movement and maintaining balance.', 'options' => [['A', 'Cerebrum', false], ['B', 'Cerebellum', true], ['C', 'Medulla oblongata', false], ['D', 'Hypothalamus', false]]],
        ['subject' => 'biology', 'topic' => 'human-physiology', 'difficulty' => 'easy', 'question' => 'What is the structural and functional unit of the kidney?', 'explanation' => 'The nephron is the microscopic filtering unit of the kidney; each human kidney contains close to a million nephrons.', 'options' => [['A', 'Neuron', false], ['B', 'Nephron', true], ['C', 'Alveolus', false], ['D', 'Glomerulus only', false]]],
        ['subject' => 'biology', 'topic' => 'human-physiology', 'difficulty' => 'easy', 'question' => 'Which structure is known as the natural pacemaker of the human heart?', 'explanation' => 'The sinoatrial (SA) node in the right atrium spontaneously generates the impulses that set the heart rhythm.', 'options' => [['A', 'Atrioventricular node', false], ['B', 'Sinoatrial node', true], ['C', 'Bundle of His', false], ['D', 'Purkinje fibres', false]]],
        ['subject' => 'biology', 'topic' => 'human-physiology', 'difficulty' => 'easy', 'question' => 'Which pigment in red blood cells is chiefly responsible for transporting oxygen?', 'explanation' => 'Haemoglobin binds oxygen in the lungs and releases it in the tissues, carrying most of the oxygen in blood.', 'options' => [['A', 'Myoglobin', false], ['B', 'Melanin', false], ['C', 'Haemoglobin', true], ['D', 'Bilirubin', false]]],
        ['subject' => 'biology', 'topic' => 'human-physiology', 'difficulty' => 'easy', 'question' => 'In the lungs, exchange of gases between air and blood occurs across which structures?', 'explanation' => 'The thin-walled alveoli provide a large moist surface where oxygen and carbon dioxide diffuse between air and blood.', 'options' => [['A', 'Bronchi', false], ['B', 'Trachea', false], ['C', 'Alveoli', true], ['D', 'Pleura', false]]],
        ['subject' => 'biology', 'topic' => 'human-physiology', 'difficulty' => 'easy', 'question' => 'What is the structural and functional unit of the nervous system?', 'explanation' => 'The neuron is the specialised cell that conducts nerve impulses and forms the basic unit of the nervous system.', 'options' => [['A', 'Nephron', false], ['B', 'Neuron', true], ['C', 'Axon', false], ['D', 'Synapse', false]]],
        ['subject' => 'biology', 'topic' => 'human-physiology', 'difficulty' => 'medium', 'question' => 'Approximately what is the tidal volume of air in a healthy resting adult during one normal breath?', 'explanation' => 'Tidal volume, the air moved in or out during a normal quiet breath, is about 500 mL in an average healthy adult male (roughly 400 mL in a female).', 'options' => [['A', '500 mL', true], ['B', '1500 mL', false], ['C', '2500 mL', false], ['D', '4500 mL', false]]],
        ['subject' => 'biology', 'topic' => 'human-physiology', 'difficulty' => 'medium', 'question' => 'In what form is the largest proportion of carbon dioxide transported in human blood?', 'explanation' => 'Most carbon dioxide is carried as bicarbonate ions formed in red blood cells by the enzyme carbonic anhydrase.', 'options' => [['A', 'Dissolved gas in plasma', false], ['B', 'Bound to haemoglobin as carbaminohaemoglobin', false], ['C', 'As bicarbonate ions', true], ['D', 'As carbon monoxide', false]]],
        ['subject' => 'biology', 'topic' => 'human-physiology', 'difficulty' => 'medium', 'question' => 'Which trace element is essential for the synthesis of thyroxine by the thyroid gland?', 'explanation' => 'Iodine is a necessary component of thyroid hormones; its deficiency can lead to goitre.', 'options' => [['A', 'Iron', false], ['B', 'Calcium', false], ['C', 'Iodine', true], ['D', 'Zinc', false]]],
        ['subject' => 'biology', 'topic' => 'human-physiology', 'difficulty' => 'medium', 'question' => 'The hormone adrenaline, released during stress, is secreted by which part of the adrenal gland?', 'explanation' => 'Adrenaline (epinephrine) is produced by the adrenal medulla, the central region of the adrenal gland.', 'options' => [['A', 'Adrenal cortex', false], ['B', 'Adrenal medulla', true], ['C', 'Zona glomerulosa', false], ['D', 'Renal pelvis', false]]],
        ['subject' => 'biology', 'topic' => 'human-physiology', 'difficulty' => 'medium', 'question' => 'What is the approximate normal resting blood pressure of a healthy young adult?', 'explanation' => 'A typical healthy blood pressure is about 120/80 mm Hg, representing systolic over diastolic pressure.', 'options' => [['A', '80/50 mm Hg', false], ['B', '120/80 mm Hg', true], ['C', '160/100 mm Hg', false], ['D', '200/120 mm Hg', false]]],
        ['subject' => 'biology', 'topic' => 'human-physiology', 'difficulty' => 'medium', 'question' => 'Glucagon, which raises blood glucose levels, is produced by which cells of the pancreas?', 'explanation' => 'The alpha cells of the islets of Langerhans secrete glucagon, which stimulates breakdown of glycogen in the liver.', 'options' => [['A', 'Beta cells', false], ['B', 'Alpha cells', true], ['C', 'Delta cells', false], ['D', 'Acinar cells', false]]],
        ['subject' => 'biology', 'topic' => 'human-physiology', 'difficulty' => 'medium', 'question' => 'In the nephron, initial filtration of blood plasma takes place at which structure?', 'explanation' => 'Blood is filtered in the glomerulus, a tuft of capillaries enclosed by the Bowman\'s capsule, forming the filtrate.', 'options' => [['A', 'Loop of Henle', false], ['B', 'Collecting duct', false], ['C', 'Glomerulus', true], ['D', 'Distal tubule', false]]],
        ['subject' => 'biology', 'topic' => 'human-physiology', 'difficulty' => 'hard', 'question' => 'According to the Bohr effect, a fall in blood pH has what effect on the affinity of haemoglobin for oxygen?', 'explanation' => 'A lower pH (higher carbon dioxide) reduces haemoglobin\'s affinity for oxygen, promoting oxygen release to active tissues.', 'options' => [['A', 'It increases oxygen affinity', false], ['B', 'It decreases oxygen affinity', true], ['C', 'It has no effect on affinity', false], ['D', 'It permanently denatures haemoglobin', false]]],
        ['subject' => 'biology', 'topic' => 'human-physiology', 'difficulty' => 'hard', 'question' => 'What is the intrinsic firing rate of the sinoatrial node before it is slowed by vagal (parasympathetic) tone at rest?', 'explanation' => 'The SA node has an intrinsic firing rate of 100 to 110 depolarisations per minute, but resting vagal tone lowers the actual heart rate to about 60 to 80 beats per minute.', 'options' => [['A', 'About 40 beats per minute', false], ['B', 'About 70 beats per minute', false], ['C', 'About 100 beats per minute', true], ['D', 'About 150 beats per minute', false]]],
        ['subject' => 'biology', 'topic' => 'human-physiology', 'difficulty' => 'hard', 'question' => 'Which enzyme in red blood cells catalyses the rapid conversion of carbon dioxide and water into carbonic acid?', 'explanation' => 'Carbonic anhydrase speeds the reaction of carbon dioxide with water, enabling bicarbonate transport of carbon dioxide.', 'options' => [['A', 'Carbonic anhydrase', true], ['B', 'Catalase', false], ['C', 'Amylase', false], ['D', 'Peptidase', false]]],
        ['subject' => 'biology', 'topic' => 'human-physiology', 'difficulty' => 'hard', 'question' => 'How many oxygen molecules can a single haemoglobin molecule carry when fully saturated?', 'explanation' => 'Each haemoglobin molecule has four haem groups and can bind up to four oxygen molecules at full saturation.', 'options' => [['A', 'One', false], ['B', 'Two', false], ['C', 'Four', true], ['D', 'Eight', false]]],

        ['subject' => 'biology', 'topic' => 'digestive-system', 'difficulty' => 'medium', 'question' => 'Where does most digestion and absorption of nutrients occur?', 'explanation' => 'The small intestine is the main site of nutrient digestion and absorption.', 'options' => [['A', 'Stomach', false], ['B', 'Small intestine', true], ['C', 'Large intestine', false], ['D', 'Esophagus', false]]],
        ['subject' => 'biology', 'topic' => 'digestive-system', 'difficulty' => 'medium', 'question' => 'Which organ produces bile to help digest fats?', 'explanation' => 'The liver produces bile, which is stored in the gallbladder and helps emulsify fats.', 'options' => [['A', 'Pancreas', false], ['B', 'Liver', true], ['C', 'Gallbladder', false], ['D', 'Stomach', false]]],
        ['subject' => 'biology', 'topic' => 'digestive-system', 'difficulty' => 'medium', 'question' => 'What is the main function of the large intestine?', 'explanation' => 'The large intestine mainly absorbs water and forms solid waste.', 'options' => [['A', 'Protein digestion', false], ['B', 'Absorption of water', true], ['C', 'Fat digestion', false], ['D', 'Enzyme production', false]]],
        ['subject' => 'biology', 'topic' => 'digestive-system', 'difficulty' => 'easy', 'question' => 'Which enzyme in the stomach helps digest proteins?', 'explanation' => 'Pepsin, activated by stomach acid, breaks down proteins into peptides.', 'options' => [['A', 'Pepsin', true], ['B', 'Amylase', false], ['C', 'Lipase', false], ['D', 'Maltase', false]]],
        ['subject' => 'biology', 'topic' => 'digestive-system', 'difficulty' => 'easy', 'question' => 'The gallbladder stores which digestive substance?', 'explanation' => 'The gallbladder stores and concentrates bile produced by the liver.', 'options' => [['A', 'Enzymes', false], ['B', 'Bile', true], ['C', 'Acid', false], ['D', 'Mucus', false]]],
        ['subject' => 'biology', 'topic' => 'digestive-system', 'difficulty' => 'medium', 'question' => 'Peristalsis refers to:', 'explanation' => 'Peristalsis is the wave-like muscle contraction that moves food through the digestive tract.', 'options' => [['A', 'Chemical digestion', false], ['B', 'Wave-like muscle contractions moving food', true], ['C', 'Absorption of nutrients', false], ['D', 'Enzyme secretion', false]]],
        ['subject' => 'biology', 'topic' => 'digestive-system', 'difficulty' => 'easy', 'question' => 'Which part of the digestive system is called the "food pipe"?', 'explanation' => 'The esophagus carries food from the throat to the stomach.', 'options' => [['A', 'Trachea', false], ['B', 'Esophagus', true], ['C', 'Larynx', false], ['D', 'Pharynx', false]]],
        ['subject' => 'biology', 'topic' => 'digestive-system', 'difficulty' => 'medium', 'question' => "The stomach's highly acidic environment is mainly due to:", 'explanation' => 'Gastric glands secrete hydrochloric acid, which aids digestion and kills pathogens.', 'options' => [['A', 'Hydrochloric acid', true], ['B', 'Sulfuric acid', false], ['C', 'Acetic acid', false], ['D', 'Citric acid', false]]],
        ['subject' => 'biology', 'topic' => 'digestive-system', 'difficulty' => 'easy', 'question' => 'Which is the largest gland in the human body?', 'explanation' => 'The liver is the largest gland in the body and produces bile that aids in fat digestion.', 'options' => [['A', 'Pancreas', false], ['B', 'Liver', true], ['C', 'Salivary gland', false], ['D', 'Thyroid', false]]],
        ['subject' => 'biology', 'topic' => 'digestive-system', 'difficulty' => 'easy', 'question' => 'Salivary amylase present in the mouth begins the digestion of which nutrient?', 'explanation' => 'Salivary amylase (ptyalin) starts breaking down starch into simpler sugars in the mouth.', 'options' => [['A', 'Proteins', false], ['B', 'Starch', true], ['C', 'Fats', false], ['D', 'Nucleic acids', false]]],
        ['subject' => 'biology', 'topic' => 'digestive-system', 'difficulty' => 'easy', 'question' => 'The vermiform appendix in humans is attached to which part of the large intestine?', 'explanation' => 'The appendix, generally considered a vestigial organ, is a narrow tube attached to the caecum.', 'options' => [['A', 'Rectum', false], ['B', 'Caecum', true], ['C', 'Transverse colon', false], ['D', 'Duodenum', false]]],
        ['subject' => 'biology', 'topic' => 'digestive-system', 'difficulty' => 'easy', 'question' => 'What are the final products of protein digestion that are absorbed by the body?', 'explanation' => 'Proteins are ultimately broken down into amino acids, which are absorbed in the small intestine.', 'options' => [['A', 'Fatty acids', false], ['B', 'Glucose', false], ['C', 'Amino acids', true], ['D', 'Glycerol', false]]],
        ['subject' => 'biology', 'topic' => 'digestive-system', 'difficulty' => 'medium', 'question' => 'Which cells of the gastric glands secrete pepsinogen, the inactive precursor of pepsin?', 'explanation' => 'Chief cells secrete pepsinogen, which is activated to pepsin by the hydrochloric acid in the stomach.', 'options' => [['A', 'Parietal cells', false], ['B', 'Chief cells', true], ['C', 'Goblet cells', false], ['D', 'G cells', false]]],
        ['subject' => 'biology', 'topic' => 'digestive-system', 'difficulty' => 'medium', 'question' => 'Hydrochloric acid in the stomach is secreted by which specialised cells?', 'explanation' => 'Parietal (oxyntic) cells of the gastric glands secrete hydrochloric acid and intrinsic factor.', 'options' => [['A', 'Chief cells', false], ['B', 'Mucous neck cells', false], ['C', 'Parietal cells', true], ['D', 'Enteroendocrine cells', false]]],
        ['subject' => 'biology', 'topic' => 'digestive-system', 'difficulty' => 'medium', 'question' => 'The protein-digesting enzyme trypsin is produced by which organ and works best in what conditions?', 'explanation' => 'Trypsin is secreted by the pancreas and acts on proteins in the alkaline environment of the small intestine.', 'options' => [['A', 'Stomach, in acidic conditions', false], ['B', 'Pancreas, in alkaline conditions', true], ['C', 'Liver, in neutral conditions', false], ['D', 'Salivary glands, in acidic conditions', false]]],
        ['subject' => 'biology', 'topic' => 'digestive-system', 'difficulty' => 'medium', 'question' => 'What is the main role of bile in the digestion of fats?', 'explanation' => 'Bile contains no digestive enzyme; its salts emulsify large fat droplets into smaller ones for enzyme action.', 'options' => [['A', 'It hydrolyses proteins', false], ['B', 'It emulsifies fats', true], ['C', 'It digests starch', false], ['D', 'It absorbs vitamins', false]]],
        ['subject' => 'biology', 'topic' => 'digestive-system', 'difficulty' => 'medium', 'question' => 'Finger-like projections called villi in the small intestine mainly serve what purpose?', 'explanation' => 'Villi greatly increase the internal surface area of the small intestine, improving absorption of nutrients.', 'options' => [['A', 'Secreting hydrochloric acid', false], ['B', 'Increasing surface area for absorption', true], ['C', 'Producing bile', false], ['D', 'Storing digested food', false]]],
        ['subject' => 'biology', 'topic' => 'digestive-system', 'difficulty' => 'medium', 'question' => 'Intrinsic factor, secreted by the stomach, is essential for the absorption of which vitamin?', 'explanation' => 'Intrinsic factor produced by parietal cells is required for absorption of vitamin B12 in the small intestine.', 'options' => [['A', 'Vitamin C', false], ['B', 'Vitamin B12', true], ['C', 'Vitamin D', false], ['D', 'Vitamin K', false]]],
        ['subject' => 'biology', 'topic' => 'digestive-system', 'difficulty' => 'medium', 'question' => 'Which organ secretes digestive enzymes as well as the hormones insulin and glucagon?', 'explanation' => 'The pancreas is a dual gland that releases digestive enzymes into the intestine and hormones into the blood.', 'options' => [['A', 'Liver', false], ['B', 'Pancreas', true], ['C', 'Gallbladder', false], ['D', 'Spleen', false]]],
        ['subject' => 'biology', 'topic' => 'digestive-system', 'difficulty' => 'hard', 'question' => 'In the duodenum, which enzyme activates trypsinogen into active trypsin?', 'explanation' => 'Enterokinase (enteropeptidase) secreted by the duodenum converts trypsinogen into active trypsin, which then activates other pancreatic proenzymes.', 'options' => [['A', 'Pepsin', false], ['B', 'Enterokinase', true], ['C', 'Amylase', false], ['D', 'Lactase', false]]],
        ['subject' => 'biology', 'topic' => 'digestive-system', 'difficulty' => 'hard', 'question' => 'The digested products of fat are absorbed into which structures present in the intestinal villi?', 'explanation' => 'Fatty acids and glycerol are absorbed into the lacteals, the lymphatic vessels within the villi, rather than into blood capillaries.', 'options' => [['A', 'Blood capillaries', false], ['B', 'Lacteals', true], ['C', 'Crypts of Lieberkuhn', false], ['D', 'Brunner\'s glands', false]]],
        ['subject' => 'biology', 'topic' => 'digestive-system', 'difficulty' => 'hard', 'question' => 'What is the approximate pH range of the acidic contents of the human stomach?', 'explanation' => 'Gastric contents are highly acidic, with a pH of roughly 1.5 to 3.5 maintained by hydrochloric acid from parietal cells.', 'options' => [['A', '1.5 to 3.5', true], ['B', '5.0 to 6.0', false], ['C', '7.0 to 7.5', false], ['D', '8.0 to 9.0', false]]],
        ['subject' => 'biology', 'topic' => 'digestive-system', 'difficulty' => 'hard', 'question' => 'Pancreatic lipase digests fats to produce which end products?', 'explanation' => 'Pancreatic lipase hydrolyses triglycerides into fatty acids and glycerol (and monoglycerides) for absorption.', 'options' => [['A', 'Amino acids and peptides', false], ['B', 'Glucose and galactose', false], ['C', 'Fatty acids and glycerol', true], ['D', 'Maltose and dextrin', false]]],

        ['subject' => 'biology', 'topic' => 'circulatory-system', 'difficulty' => 'easy', 'question' => 'How many chambers does the human heart have?', 'explanation' => 'The human heart has four chambers: two atria and two ventricles.', 'options' => [['A', '2', false], ['B', '4', true], ['C', '3', false], ['D', '5', false]]],
        ['subject' => 'biology', 'topic' => 'circulatory-system', 'difficulty' => 'easy', 'question' => 'Which blood vessels carry blood away from the heart?', 'explanation' => 'Arteries carry oxygenated blood away from the heart (with the exception of the pulmonary artery).', 'options' => [['A', 'Veins', false], ['B', 'Arteries', true], ['C', 'Capillaries', false], ['D', 'Venules', false]]],
        ['subject' => 'biology', 'topic' => 'circulatory-system', 'difficulty' => 'easy', 'question' => 'Which blood cells are responsible for carrying oxygen?', 'explanation' => 'Red blood cells contain hemoglobin, which binds and transports oxygen.', 'options' => [['A', 'White blood cells', false], ['B', 'Red blood cells', true], ['C', 'Platelets', false], ['D', 'Plasma cells', false]]],
        ['subject' => 'biology', 'topic' => 'circulatory-system', 'difficulty' => 'medium', 'question' => 'What is the function of platelets in the blood?', 'explanation' => 'Platelets help blood clot to stop bleeding after injury.', 'options' => [['A', 'Fighting infection', false], ['B', 'Blood clotting', true], ['C', 'Carrying oxygen', false], ['D', 'Transporting hormones', false]]],
        ['subject' => 'biology', 'topic' => 'circulatory-system', 'difficulty' => 'medium', 'question' => 'Which blood type is known as the universal donor?', 'explanation' => 'O negative blood lacks A, B, and Rh antigens, making it compatible with most recipients.', 'options' => [['A', 'AB', false], ['B', 'O negative', true], ['C', 'A positive', false], ['D', 'B negative', false]]],
        ['subject' => 'biology', 'topic' => 'circulatory-system', 'difficulty' => 'medium', 'question' => 'The pulmonary artery carries blood from the heart to the:', 'explanation' => 'The pulmonary artery carries deoxygenated blood from the right ventricle to the lungs.', 'options' => [['A', 'Kidneys', false], ['B', 'Lungs', true], ['C', 'Liver', false], ['D', 'Brain', false]]],
        ['subject' => 'biology', 'topic' => 'circulatory-system', 'difficulty' => 'hard', 'question' => 'Which chamber of the heart pumps oxygenated blood to the body?', 'explanation' => 'The left ventricle pumps oxygenated blood through the aorta to the rest of the body.', 'options' => [['A', 'Right atrium', false], ['B', 'Left ventricle', true], ['C', 'Right ventricle', false], ['D', 'Left atrium', false]]],
        ['subject' => 'biology', 'topic' => 'circulatory-system', 'difficulty' => 'easy', 'question' => 'What is the average number of times a healthy heart beats per minute at rest?', 'explanation' => 'A normal resting heart rate for adults is typically 60-100 beats per minute.', 'options' => [['A', '60-100', true], ['B', '150-180', false], ['C', '30-50', false], ['D', '200-220', false]]],

        ['subject' => 'biology', 'topic' => 'ecology', 'difficulty' => 'easy', 'question' => 'The study of interactions between organisms and their environment is called:', 'explanation' => 'Ecology examines relationships between living organisms and their surroundings.', 'options' => [['A', 'Genetics', false], ['B', 'Ecology', true], ['C', 'Physiology', false], ['D', 'Taxonomy', false]]],
        ['subject' => 'biology', 'topic' => 'ecology', 'difficulty' => 'medium', 'question' => 'A community of interacting organisms and their physical environment is called a(n):', 'explanation' => 'An ecosystem includes living organisms and the non-living environment they interact with.', 'options' => [['A', 'Population', false], ['B', 'Ecosystem', true], ['C', 'Biome', false], ['D', 'Habitat', false]]],
        ['subject' => 'biology', 'topic' => 'ecology', 'difficulty' => 'easy', 'question' => 'Organisms that produce their own food using sunlight are called:', 'explanation' => 'Producers, like plants, use photosynthesis to create their own energy.', 'options' => [['A', 'Consumers', false], ['B', 'Producers', true], ['C', 'Decomposers', false], ['D', 'Predators', false]]],
        ['subject' => 'biology', 'topic' => 'ecology', 'difficulty' => 'easy', 'question' => 'What is the primary source of energy for most ecosystems?', 'explanation' => 'The Sun provides the energy that drives photosynthesis and most food chains.', 'options' => [['A', 'Wind', false], ['B', 'The Sun', true], ['C', 'Water', false], ['D', 'Soil nutrients', false]]],
        ['subject' => 'biology', 'topic' => 'ecology', 'difficulty' => 'medium', 'question' => 'Organisms that break down dead organic matter are called:', 'explanation' => 'Decomposers, like fungi and bacteria, recycle nutrients from dead material.', 'options' => [['A', 'Producers', false], ['B', 'Decomposers', true], ['C', 'Herbivores', false], ['D', 'Carnivores', false]]],
        ['subject' => 'biology', 'topic' => 'ecology', 'difficulty' => 'easy', 'question' => 'A food chain typically begins with:', 'explanation' => 'Food chains start with producers, usually plants, which convert sunlight into energy.', 'options' => [['A', 'Carnivores', false], ['B', 'Producers/plants', true], ['C', 'Decomposers', false], ['D', 'Omnivores', false]]],
        ['subject' => 'biology', 'topic' => 'ecology', 'difficulty' => 'medium', 'question' => 'The gradual and predictable change in species composition of a habitat over time is called:', 'explanation' => 'Ecological succession describes the change in a community\'s structure over time.', 'options' => [['A', 'Succession', true], ['B', 'Migration', false], ['C', 'Adaptation', false], ['D', 'Symbiosis', false]]],
        ['subject' => 'biology', 'topic' => 'ecology', 'difficulty' => 'medium', 'question' => 'A relationship where both organisms benefit is called:', 'explanation' => 'Mutualism is a symbiotic relationship benefiting both participating species.', 'options' => [['A', 'Parasitism', false], ['B', 'Mutualism', true], ['C', 'Commensalism', false], ['D', 'Predation', false]]],

        ['subject' => 'biology', 'topic' => 'plant-biology', 'difficulty' => 'easy', 'question' => 'Which process do plants use to make their own food?', 'explanation' => 'Photosynthesis converts light energy, water, and carbon dioxide into glucose and oxygen.', 'options' => [['A', 'Respiration', false], ['B', 'Photosynthesis', true], ['C', 'Transpiration', false], ['D', 'Fermentation', false]]],
        ['subject' => 'biology', 'topic' => 'plant-biology', 'difficulty' => 'easy', 'question' => 'The green pigment in plants that absorbs sunlight is called:', 'explanation' => 'Chlorophyll absorbs light energy for photosynthesis and gives plants their green color.', 'options' => [['A', 'Carotene', false], ['B', 'Chlorophyll', true], ['C', 'Xanthophyll', false], ['D', 'Anthocyanin', false]]],
        ['subject' => 'biology', 'topic' => 'plant-biology', 'difficulty' => 'easy', 'question' => 'Which part of the plant absorbs water and minerals from the soil?', 'explanation' => 'Roots absorb water and dissolved minerals from the soil.', 'options' => [['A', 'Leaves', false], ['B', 'Roots', true], ['C', 'Stem', false], ['D', 'Flower', false]]],
        ['subject' => 'biology', 'topic' => 'plant-biology', 'difficulty' => 'medium', 'question' => 'Photosynthesis primarily takes place in which organelle?', 'explanation' => 'Chloroplasts contain chlorophyll and are the site of photosynthesis.', 'options' => [['A', 'Mitochondria', false], ['B', 'Chloroplast', true], ['C', 'Nucleus', false], ['D', 'Vacuole', false]]],
        ['subject' => 'biology', 'topic' => 'plant-biology', 'difficulty' => 'medium', 'question' => 'What gas do plants absorb from the atmosphere during photosynthesis?', 'explanation' => 'Plants take in carbon dioxide and release oxygen during photosynthesis.', 'options' => [['A', 'Oxygen', false], ['B', 'Carbon dioxide', true], ['C', 'Nitrogen', false], ['D', 'Hydrogen', false]]],
        ['subject' => 'biology', 'topic' => 'plant-biology', 'difficulty' => 'medium', 'question' => 'The loss of water vapor from plant leaves is called:', 'explanation' => 'Transpiration is the evaporation of water from plant leaves, mainly through stomata.', 'options' => [['A', 'Photosynthesis', false], ['B', 'Transpiration', true], ['C', 'Respiration', false], ['D', 'Germination', false]]],
        ['subject' => 'biology', 'topic' => 'plant-biology', 'difficulty' => 'medium', 'question' => 'Which part of the flower produces pollen?', 'explanation' => 'The stamen, the male reproductive part of a flower, produces pollen.', 'options' => [['A', 'Pistil', false], ['B', 'Stamen', true], ['C', 'Sepal', false], ['D', 'Petal', false]]],
        ['subject' => 'biology', 'topic' => 'plant-biology', 'difficulty' => 'easy', 'question' => 'What is the process by which a seed develops into a new plant?', 'explanation' => 'Germination is the process by which a seed sprouts and develops into a seedling.', 'options' => [['A', 'Pollination', false], ['B', 'Germination', true], ['C', 'Fertilization', false], ['D', 'Propagation', false]]],

        ['subject' => 'biology', 'topic' => 'microbiology', 'difficulty' => 'medium', 'question' => 'Which scientist is credited with developing the germ theory of disease?', 'explanation' => 'Louis Pasteur\'s experiments established that microorganisms cause disease.', 'options' => [['A', 'Charles Darwin', false], ['B', 'Louis Pasteur', true], ['C', 'Gregor Mendel', false], ['D', 'Isaac Newton', false]]],
        ['subject' => 'biology', 'topic' => 'microbiology', 'difficulty' => 'medium', 'question' => 'Bacteria are classified as which type of organism?', 'explanation' => 'Bacteria are prokaryotes, lacking a membrane-bound nucleus.', 'options' => [['A', 'Eukaryotic', false], ['B', 'Prokaryotic', true], ['C', 'Multicellular', false], ['D', 'Viral', false]]],
        ['subject' => 'biology', 'topic' => 'microbiology', 'difficulty' => 'easy', 'question' => 'Which microorganisms are used to make yogurt and cheese?', 'explanation' => 'Beneficial bacteria ferment milk to produce yogurt and cheese.', 'options' => [['A', 'Viruses', false], ['B', 'Bacteria', true], ['C', 'Protozoa', false], ['D', 'Prions', false]]],
        ['subject' => 'biology', 'topic' => 'microbiology', 'difficulty' => 'medium', 'question' => 'Antibiotics are effective against which type of pathogen?', 'explanation' => 'Antibiotics target bacterial cell processes and are ineffective against viruses.', 'options' => [['A', 'Viruses', false], ['B', 'Bacteria', true], ['C', 'Prions', false], ['D', 'All pathogens equally', false]]],
        ['subject' => 'biology', 'topic' => 'microbiology', 'difficulty' => 'easy', 'question' => 'Which scientist discovered penicillin?', 'explanation' => 'Alexander Fleming discovered penicillin in 1928 from Penicillium mold.', 'options' => [['A', 'Alexander Fleming', true], ['B', 'Robert Koch', false], ['C', 'Edward Jenner', false], ['D', 'Joseph Lister', false]]],
        ['subject' => 'biology', 'topic' => 'microbiology', 'difficulty' => 'medium', 'question' => 'Viruses differ from bacteria mainly because viruses:', 'explanation' => 'Viruses are obligate parasites and require a host cell\'s machinery to reproduce.', 'options' => [['A', 'Are larger', false], ['B', 'Cannot reproduce without a host cell', true], ['C', 'Have a nucleus', false], ['D', 'Are always harmful', false]]],
        ['subject' => 'biology', 'topic' => 'microbiology', 'difficulty' => 'medium', 'question' => 'What is the process of using heat to kill harmful microorganisms in food called?', 'explanation' => 'Pasteurization uses controlled heat to destroy pathogens in food and beverages.', 'options' => [['A', 'Fermentation', false], ['B', 'Pasteurization', true], ['C', 'Sterilization', false], ['D', 'Distillation', false]]],
        ['subject' => 'biology', 'topic' => 'microbiology', 'difficulty' => 'medium', 'question' => 'Fungi obtain nutrients by:', 'explanation' => 'Fungi are heterotrophs that absorb nutrients from organic matter in their environment.', 'options' => [['A', 'Photosynthesis', false], ['B', 'Absorbing organic matter', true], ['C', 'Chemosynthesis', false], ['D', 'Filter feeding', false]]],
    ];

    $questions = array_merge(
        $questions,
        require __DIR__ . '/data/mcq_chemistry_physics.php',
        require __DIR__ . '/data/mcq_math_english.php',
        require __DIR__ . '/data/mcq_gk_cs.php',
        require __DIR__ . '/data/mcq_urdu_islamic.php'
    );

    $findSubject = $pdo->prepare('SELECT id FROM mcq_subjects WHERE slug = ?');
    $findTopic = $pdo->prepare('SELECT id FROM mcq_topics WHERE slug = ? AND subject_id = ?');
    $findExisting = $pdo->prepare('SELECT id FROM mcq_questions WHERE question_text = ? LIMIT 1');
    $insertMcq = $pdo->prepare(
        'INSERT INTO mcq_questions (subject_id, topic_id, question_text, explanation, difficulty, created_at, updated_at)
         VALUES (?, ?, ?, ?, ?, NOW(), NOW())'
    );
    $insertOption = $pdo->prepare(
        'INSERT INTO mcq_options (mcq_id, label, option_text, is_correct, sort_order) VALUES (?, ?, ?, ?, ?)'
    );

    foreach ($questions as $q) {
        $findExisting->execute([$q['question']]);
        if ($findExisting->fetchColumn()) continue;

        $findSubject->execute([$q['subject']]);
        $subjectId = $findSubject->fetchColumn();
        if (!$subjectId) continue;

        $findTopic->execute([$q['topic'], $subjectId]);
        $topicId = $findTopic->fetchColumn() ?: null;

        $insertMcq->execute([$subjectId, $topicId, $q['question'], $q['explanation'], $q['difficulty']]);
        $mcqId = (int) $pdo->lastInsertId();

        foreach ($q['options'] as $order => $option) {
            [$label, $text, $isCorrect] = $option;
            $insertOption->execute([$mcqId, $label, $text, $isCorrect ? 1 : 0, $order]);
        }
    }
};
